version: '3'
services: 
    minio:
        image: minio/minio:RELEASE.2020-08-18T19-41-00Z
        volumes:
            - vvol:/vvol
        ports:
            - "9000:9000"
        environment: 
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
            MINIO_REGION_NAME: us-east-1
        command: server /vvol
volumes:
    vvol:
