kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32000
    hostPort: 80
  - containerPort: 30300
    hostPort: 9000
- role: worker
- role: worker